apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.virtuozzo.com
spec:
  group: virtuozzo.com
  names:
    kind: VirtualMachine
    listKind: VirtualMachineList
    plural: virtualmachines
    singular: virtualmachine
    shortNames:
      - vm
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - memory
              properties:
                memory:
                  type: integer
                  minimum: 512
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [Pending, Running, Stopped, Error]
      additionalPrinterColumns:
        - name: RAM
          type: integer
          jsonPath: .spec.memory
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
